### ISSUE TITLE
Fedora Workstation.

### ISSUE THREAD

**Issue by agirorn** [boxcutter/fedora#14]
Why are there now workstation boxes in the repository?
The ubuntu repository has Desktop with GUI enabled.

**Comment by fwilhe** [comment]
For testing my ansible playbooks for desktop systems, I would also like a box that ships gnome. Is there any chance for such a thing?

:+1: for your work anyway! I like the boxes (I use fedora and ubuntu) really a lot.

**Comment by annawake** [comment]
PRs accepted ;-)
