### ISSUE TITLE
empty /etc/machine-id on fedora

### ISSUE THREAD

**Issue by bertvv** [boxcutter/fedora#27]
issue boxcutter/centos#37 is also relevant for this base box. Maybe it's best to remove `/etc/machine-id` in the cleanup script?

**Comment by bertvv** [comment]
I found out that removing `/etc/machine-id` causes a.o. systemd-journald to fail. By creating an empty machine-id file, systemd will automatically generate a new id:

```bash
echo "" > /etc/machine-id
```

**Comment by annawake** [comment]
https://github.com/boxcutter/fedora/commit/d478532cadddc49112a5c6d5129197d4bcaa7f2c
