### ISSUE TITLE
Fedora25 is 404

### ISSUE THREAD

**Issue by lisp719** [boxcutter/fedora#29]
I used fedora 24.
I tried updating to fedora 25.
But I could not download fedora 25.

```
The box 'boxcutter/fedora25' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/boxcutter/fedora25"]
Error: The requested URL returned error: 404 Not Found
```

Thanks for your help.

**Comment by misheska** [comment]
We'll still keep the template sources up here on github, but I'm retiring the binary archive. It's a lot of work keeping the templates built and keeping up with all the vagrant/desktop virtualization changes, and I don't think it's worth the effort to do it anymore, given all the options that exist via Docker and cloud providers.
