### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by patrickmslatteryvt** [boxcutter/fedora#34]
Are these repos being maintained any more?
I note that there have been no uploads to https://app.vagrantup.com/box-cutter in over a year.
I'd be willing to maintain the repos and provide CDN space if necessary.
Thanks

**Comment by olberger** [comment]
I'd personally recommend rebuilding systematically instead of using prebuilt boxes which might contain MitM...

**Comment by patrickmslatteryvt** [comment]
@olberger Yeah, from a security standpoint you are right.
I'll close this out.
