### ISSUE TITLE
Upgrade for F28

### ISSUE THREAD

**Issue by olberger** [boxcutter/fedora#35]
In case anyone is interested in Fedora 28 support ?

I may have something working soon... unless someone beats me and forgot to push ;)

**Comment by patrickmslatteryvt** [comment]
Actually I had created a F28 branch a while back and not pushed it.
I just pushed it now if you would care to test.

**Comment by rasa** [comment]
Fixed in #36

**Comment by olberger** [comment]
Hmmm... I'm currently testing it and the -ws (workstation) flavour doesn't seem to work re- the VirtualBox extensions.

The build process exhibits:
   virtualbox-iso: Uncompressing VirtualBox 5.2.10 Guest Additions for Linux........
    virtualbox-iso: VirtualBox Guest Additions installer
    virtualbox-iso: Copying additional installer modules ...
    virtualbox-iso: Installing additional modules ...
    virtualbox-iso: VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.
    virtualbox-iso: VirtualBox Guest Additions: Look at /var/log/vboxadd-setup.log to find out what went wrong
    virtualbox-iso: VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
    virtualbox-iso: VirtualBox Guest Additions: Starting.
    virtualbox-iso: VirtualBox Guest Additions: modprobe vboxsf failed

I guess there are issues with the fact that the modules are already included by Fedora... so maybe the virtualbox provisioning script may need to be adjusted / removed... or this just works with the -server flavour, which I haven't yet tested.

Will open another separate issue, now that it's merged.
