### ISSUE TITLE
Fedora 22 32-bit template not working

### ISSUE THREAD

**Issue by annawake** [boxcutter/fedora#4]
Does not properly install guest additions on 32-bit Fedora 22, so shared folders do not work

**Comment by bertvv** [comment]
The error message I see suggests that the Guest Additions installation needs `kernel-pae-devel` which was removed from the `ks-fedora22.cfg` in commit 837c972. Maybe it'll work by installing this from `scripts/vmtool.sh`? E.g. something like

``` Bash
if [ "$(uname -p)" = "i386" ]; then
    ${PKG_MGR} install -y kernel-pae-devel
fi
```

Sorry, I don't have time to try this myself right now...

**Comment by annawake** [comment]
That doesn't seem to help

**Comment by annawake** [comment]
Fedora 22 EOL
