### ISSUE TITLE
Vmware Fedora 22: Waiting for HGFS kernel module to load takes endlessy

### ISSUE THREAD

**Issue by schmitch** [boxcutter/fedora#5]
Hello, currently I created a VM with boxcutter/fedora and packer.io and somehow starting the vm with vagrant up hangs on:

> ==> default: Waiting for HGFS kernel module to load...

and after a while there is

> The HGFS kernel module was not found on the running virtual machine.
> This must be installed for shared folders to work properly. Please
> install the VMware tools within the guest and try again. Note that
> the VMware tools installation will succeed even if HGFS fails
> to properly install. Carefully read the output of the VMware tools
> installation to verify the HGFS kernel modules were installed properly.

Looks like the patch is just too old

**Comment by misheska** [comment]
Never worked in the first place - there's a filter in the Makefile to not bother building Fedora 22 for VMware (or Fedora 21 for that matter):

`VMWARE_TEMPLATE_FILENAMES = $(filter-out fedora21-i386.json fedora21.json fedora22-i386.json fedora22.json,$(TEMPLATE_FILENAMES))`

Always willing to take a PR with a patch, if you come up with one.

**Comment by akaspin** [comment]
Get one on boxcutter/fedora-21
